name: eqms_test
description: A merged Flutter project for EQSI

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  flutter_local_notifications: ^15.1.0+1
  url_launcher: ^6.1.12
  http: ^1.1.0
  google_maps_flutter: ^2.3.1
  geolocator: ^9.0.2
  firebase_database: ^10.2.4
  dio: ^5.3.0
  retrofit: ^4.0.1
  retrofit_generator: ^7.0.8
  build_runner: ^2.4.6
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  google_maps_flutter_android: ^2.4.15
  google_maps_flutter_platform_interface: ^2.4.0
  google_maps_cluster_manager: ^3.0.0+1
  flutter_svg: ^2.0.7
  provider: ^6.0.5
  group_button: ^5.3.2
  syncfusion_flutter_datagrid: ^22.2.7
  syncfusion_flutter_core: ^22.2.7
  flutter_pdfview: ^1.3.1
  path_provider: ^2.0.15
  permission_handler: ^10.1.1
  share: ^2.0.4
  flutter_cache_manager: ^3.1.2
  flutter_phone_direct_caller: ^2.1.1
  rflutter_alert: ^2.0.7
  shared_preferences: ^2.2.0
  android_intent_plus: ^4.0.2
  pie_chart: ^5.3.2
  fl_chart: ^0.63.0
  intl: ^0.17.0
  page_transition: ^2.0.9
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  fluttertoast: ^8.2.2
  easy_debounce: ^2.0.3
  youtube_player_iframe: ^4.0.0
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/maps-and-flags.png
    - assets/eq_info.svg
    - assets/eq_safety.svg
    - assets/eq_safety_selected.svg
    - assets/sensor_info.svg
    - assets/sensor_map.svg
    - assets/setting.svg
    - assets/earthquake.svg
    - assets/emergeInst.svg
    - assets/shelter.svg
    - assets/traumaCenter.svg
    - assets/sensor.svg
    - assets/
    - images/
